### ISSUE TITLE
Compatibility questions

### ISSUE THREAD

**Issue by Winddbourne** [Terpo/Waterworks#16]
This is a very interesting mod; and it could be very useful. I do have some questions though before I consider adding it to a mod pack I'm fiddling around with. 

1) Is it compatible with Tough as Nails? Specifically do the rain collectors provide clean water like the rain collector from that mod? I'd hate to add in a rain collector that results in dirty water and confuse players. If ground water from the pump is dirty nobody will be surprised. lol

2) Power . . . I'm assuming forge energy would be compatible with most/all forge power types like RF, EU, and Tesla? Currently I haven't got any power generation going in my pack but I might include forestry to power something like this.

**Comment by Terpo** [comment]
1) The released version does not have support for water bottles at all. These don't use the new forge system to fill containers. I already added a way to fill them manual, but thats something for the next release. I need to take a look into it for automation of it.  (see #15 )

I'll test my latest changes with Tough as Nails and see if it works. 

2) FE needs to be implemented by the mods, but it's not that hard. I tested everything with Actually Additions so far. Tech Reborn should also work. I will test some more mods later on.

**Comment by Terpo** [comment]
Tested some of the current 1.11 tech mods with my mod: Results -> [wiki](https://github.com/Terpo/Waterworks/wiki/forge_energy)

Rain Tank, Rain Collector Controller and Groundwater Pump will produce normal Water Bottles when Tough as Nails is installed. 
When I figured out how to use its API, I may change the water bottles in the Groundwater Pump to Filtered Water Bottles.

**Comment by Terpo** [comment]
Added full Glass Bottle compatibility in:
730645f4cc1d3b50fcd733fc06c6c4eefb9b39b9
4cb652ee5e096f06d575c58fea8531b4b1798d49
and 
b7c4db89af178118f5a4eab9e9ed58e1343ac30a
