### ISSUE TITLE
Skyblock problem

### ISSUE THREAD

**Issue by LokyLive** [Terpo/Waterworks#37]
I'm working on a 1.12.2 skyblock modpack and i want to use the ground water pump but ofc in skyblock there is no Bedrock xD
Could you add a cfg line to disable the bedrock requirement for the ground water pump or add a craftable bedrock block ?

**Comment by Terpo** [comment]
Well, then I think the easiest way would be an option that checks if the water pipes hit y level 0 instead of bedrock. I'll see whats possible there :)

**Comment by LokyLive** [comment]
thanks ,p
