### ISSUE TITLE
Server shut down

### ISSUE THREAD

**Issue by houba1970** [Terpo/Waterworks#40]
Hi, i hope it is not my fault but when i have placed any watercollecting blok from water block and starts raining my server goes into Instant Shutdown because of ticking entity error....idk what to do....plus i must start server again and before any log in onto server i must stop rain from console because if is block loaded when its raining it will drop again.
Posting crashlog
BTW: sorry for bad english i hope you got meaning :) Good luck

[crash-2018-01-23_20.55.38-server.txt](https://github.com/Terpo/Waterworks/files/1657446/crash-2018-01-23_20.55.38-server.txt)
[crash-2018-01-23_21.02.45-server.txt](https://github.com/Terpo/Waterworks/files/1657447/crash-2018-01-23_21.02.45-server.txt)

**Comment by Terpo** [comment]
Thanks for the report. Currently looking at the code. Question for me is .... what and why should there be anything null. 
I could create a debug jar for you that could help me. All I need are the fml logs with the new file as it could get a pain to reproduce the error :).

**Comment by Terpo** [comment]
ok, no need to give a debug version to you. Its fully reproducable. I am on it.

**Comment by houba1970** [comment]
Here is FML log (idk if i send a right one but this is only what i found)

[2018-01-23-7.log](https://github.com/Terpo/Waterworks/files/1657525/2018-01-23-7.log)

**Comment by houba1970** [comment]
And i forget this is my config of waterworks maybe is something wrong there (meybe i did something wrong)
(its .txt because .cfg is not suported for upload here)

[waterworks.txt](https://github.com/Terpo/Waterworks/files/1657530/waterworks.txt)

**Comment by Terpo** [comment]
Its ok :D. My development setup is crashing as well. No I need to find a fix. I also know why its crashing. 

Nope, on your side everything is fine, no need to worry.

**Comment by Terpo** [comment]
New version landed: https://minecraft.curseforge.com/projects/waterworks/files/2523446

Let me know if anything else is broken. This issue you found was really important as a lot off stuff on server-side did not work as expected. Thanks again.
