### ISSUE TITLE
Anti-Rain Rocket drops wet sponges even in Clear Weather

### ISSUE THREAD

**Issue by Ristellise** [Terpo/Waterworks#42]
There is a gif Below:
![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/7894419/37198029-d3e57778-23b7-11e8-9eec-14f78bbdbe44.gif)

**Comment by Terpo** [comment]
That is indeed not intended.

**Comment by Terpo** [comment]
https://minecraft.curseforge.com/projects/waterworks/files/2539151 
That should be fixed.

**Comment by Ristellise** [comment]
Cheers :D Love the mod already!
