### ISSUE TITLE
Enhancement: Right Click to update Rain Collectors without a wrench

### ISSUE THREAD

**Issue by Ristellise** [Terpo/Waterworks#43]
Says on the tin, config option to not require a wrench to update the collector.

**Comment by Terpo** [comment]
Well, I think the best way would be a button in the GUI of the collector controller to search for valid collectors. Adding a config option use hands for connecting would be possible but then you get side effects when opening the GUI of the controller. Using a shift + click with hand would be problematic when placing blocks next to it. I'll put it on my todo list for now.

Can't promise any dates for this as I have a lot of things todo currently.
