### ISSUE TITLE
Add config options to disable JEI info pages

### ISSUE THREAD

**Issue by Yarden-zamir** [Terpo/Waterworks#45]
I would like to be able to disable those and use crafttwaker to add my own.

**Comment by Terpo** [comment]
Going to add a  config option for all JEI descriptions.

**Comment by Yarden-zamir** [comment]
Thank you!
About what you said about specific values, I don't know how to use variables in language files, but it did give me a semi-related [idea](https://github.com/Terpo/Waterworks/issues/46)
