### ISSUE TITLE
Minimum required to fill up a water bottle.

### ISSUE THREAD

**Issue by cheesealmighty** [Terpo/Waterworks#48]
As it stands, even if the water tank has 10mb's of water it will fill up a water bottle. 

This makes things hard if you want to make water scarce. 

I know bottles don't use the Forge's fluid system, but is it possible to add a check for minimum amount of water that has to be in the tank for a player to fill their bottles? Better if it's adjustable, but I guess 250mBs is about the standard. 

Best regards.

**Comment by Terpo** [comment]
I will take a look into it. I assume its 1.12 right?

**Comment by Terpo** [comment]
I could not reproduce this bug in the latest version of my mod. 

Even updating to the latest forge version did not change anything. I am already checking for a specific amount of water an that 1000mB for my mod.

**Comment by cheesealmighty** [comment]
Hmm. Odd. 

It's 1.12.2 yes. 

I'm using Waterworks 1.0.10 (lates available on twitch)
Forge version 23.4.2707

This is the modpack (Everything up to date): https://minecraft.curseforge.com/projects/for-a-drop-of-water/relations/dependencies

Could Thirsty Bottles from Darkhax, or Water Control Extreme by Dr_Codex cause this? They are the only mods that I know of in my modpack that affects water dynamics.

Behaviour documented here: https://puu.sh/AQS1j/0ad2518c56.mp4

Further testing showed that the *proper* rain collector stops working all together after right click.
Wooden one works fine. EDIT: This is incorrect, I just failed to set up the rain collector correctly. Sorry.

And it works the way you described, if you put it *in* the rain collector. Only the right click behaviour is borked. 

EDIT2: The behaviour persists even after removing "Thirsty bottles". Not sure what's causing it.

**Comment by Terpo** [comment]
I will take a look into this. The first thing I need to check is the right click behavior itself. A fix in the next 4-5 days will not happen for sure but I hope that I can release a new version next week. 
Thanks for all the infos so far.

**Comment by cheesealmighty** [comment]
Oh, no problem. Thank **you** for the swift reply.

**Comment by Terpo** [comment]
I did some test during the last hours. Everything I tested was direclty in the latest version of you modpack. 

If I use glass bottles in my dev environment, my rain tain is activated and handles the right click. In your mod pack my rain tank does not even know that it was clicked. So it seems another mod adds some weird right click behavior to the glass bottle and handles is poorly. As I am using a standard forge fluid tank without any magic I can not do much about it.

**Comment by cheesealmighty** [comment]
> Thirsty Bottles from Darkhax, or Water Control Extreme by Dr_Codex

Are the two mods that change water dynamics. Thirsty bottles handle the bottle mechanics in particular. Maybe ask Darkhax about it? His mods are usually pretty stable, but I haven't got a clue.

**Comment by Terpo** [comment]
I can tell you that it is not Thirsty bottles. I just tested the version from your modpack in my dev environment. In my opinion it maybe is not one of the two you mentioned but any other mod that does bullshit coremod stuff in the background. The only thing you can do it try to split up your pack locally until you find the mod. 

So try to split everything in half until my mod is working again or so. As I said, there seems no way for me to prevent that interaction as none of my code is triggered directly. If you find another candidate I can try it with this in my dev environment. Then it is possible to create a proper bug report to that mod.

**Comment by Terpo** [comment]
Closed due to 1.14 porting.
