### ISSUE TITLE
Missing item textures on Forge Version 14.23.4.2727

### ISSUE THREAD

**Issue by cheesealmighty** [Terpo/Waterworks#49]
Missing item textures on:
Forge Version 14.23.4.2727
Minecraft 1.12.2.

Rain collector, rain collector controller are missing textures, only when in inventory. They display correct textures when placed.

This happened after I updated the Forge version 2707----> 14.23.4.2727 and updated connected textures mod. 

Waterworks is the only mod affected, it seems. Everything else works fine.

https://puu.sh/AQUsl/31ca72d755.png

(Also this didn't help with my previous bug either, so, oh well.)

**Comment by Terpo** [comment]
Yeah, I saw this one while testing the latest forge. There was some change between forge version.

**Comment by Terpo** [comment]
Short update: Hopefully I got some time until this sunday to patch a few things
