### ISSUE TITLE
(1.12.2) Suggestion - Allow for generated liquids to be specified

### ISSUE THREAD

**Issue by katubug** [Terpo/Waterworks#69]
Hi! I'm working on a modpack that utilizes a water control mechanic, and I really like the idea of using this mod, particularly for the ground pump, as a way of obtaining water. However, I am also using Tough as Nails in the modpack, so I was hoping to configure your machines to produce Purified Water instead of regular. TaN does technically already have a rainwater collection device, so if this ends up not being something you want to prioritize, then I understand. I just wanted to make the suggestion, in case it vibed with you. :)

As an aside, another use case for this would be with mods that add a toxic rain mechanic (such as Twisted Tweaks or Toxic Rain), which could contaminate water in the Rain Collector. That would be more complicated, though.

In any case, thank you for the mod, and for your time!

**Comment by Terpo** [comment]
Relates to #47

---

As written, I try to backport some bugfixes in the next weeks, as 1.12 is still a really active platform. 
But no promises ;)

---

Info (for me):
- Config option for each collecting device
- First try with modid:fluid as universal option
- If thats not working do a special case for tough as nails fluid
- Always add a fallback to Minecraft water

**Comment by Terpo** [comment]
https://www.curseforge.com/minecraft/mc-mods/waterworks/files/2854122

Please try this version. I added new config options where the created fluids can be specified. With this solution it is not possible for other mods to change the collected fluids on the fly but for modpack makers it should be quite helpful. This version also includes a lot of stuff that I backported from 1.14 like full Patchouli Support :).

If you find any bugs or other stuff then simply create a new issue.

**Comment by katubug** [comment]
Just wanted to pop back and say this works perfectly, thank you very much! :)
