### ISSUE TITLE
Tag 1.16.5 on CurseForge to enable custom profiles to add the mod

### ISSUE THREAD

**Issue by paulhlschr** [Terpo/Waterworks#84]
Question/Request
Is it possible to tag Waterworks on CurseForge with 1.16.5, as custom profiles and modpacks are not able to include the mod using the CurseForge client, if the profile runs on Forge 1.16.5?

**Comment by Terpo** [comment]
I never tested my mod with 1.16.5 at this point. If it works then this should not be a problem. I may also release a new version with updated dependencies.

**Comment by Terpo** [comment]
I added the tag on the latest release, but as written, it currently untested

**Comment by Terpo** [comment]
I removed the tag again, as the mods toml from that release should not support 1.16.5

But there is a new release https://www.curseforge.com/minecraft/mc-mods/waterworks/files/3203677
